console.log("Hello Wrold");
let a = 5; 
let b = 6;
let letter = "Zain";
console.log(a+b);
console.log(typeof a);
console.log(typeof letter);
let val1 = 33;
let val2 = 66;
console.log(val1*val2); 
let c = 44.5;
let d = 55.3;
let sub = d-c;
console.log(sub);
let e=20;
let f = 10;
console.log(e/f);
